# Planner selection
base_global_planner: "navfn/NavfnROS"
base_local_planner: "teb_local_planner/TebLocalPlannerROS"

# Recovery behaviors are defined in robot folders

# Oscillation
oscillation_timeout: 10.0
oscillation_distance: 0.5

# Global planner
planner_frequency: 0.0
planner_patience: 5.0
NavfnROS:
  allow_unknown: true  # TODO: investigate this
  default_tolerance: 0.0
  # do not restrict planner
  planner_window_x: 0.0
  planner_window_y: 0.0
  # debug
  visualize_potential: false

# Local planner
controller_frequency: 25.0
controller_patience: 15.0

TebLocalPlannerROS:
 odom_topic: odom
 map_frame: map
    
 # Trajectory
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True #Change orientation if needed for path, or auto generate
 max_global_plan_lookahead_dist: 3.0
 # global_plan_viapoint_sep: 
 feasibility_check_no_poses: 5

 #ViaPoints
 global_plan_viapoint_sep: 0.2 #negative if none
 via_points_ordered: True #adhere to order of via points

 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
  type: "circular"
  radius: 0.28702 # for type "circular" https://www.zebra.com/content/dam/zebra_new_ia/en-us/zebra_dam/brochure/fetch-hmishelf-brochure-en-us.pdf
  line_start: [-0.3, 0.0] # for type "line"
  line_end: [0.3, 0.0] # for type "line"
  front_offset: 0.2 # for type "two_circles"
  front_radius: 0.2 # for type "two_circles"
  rear_offset: 0.2 # for type "two_circles"
  rear_radius: 0.2 # for type "two_circles"
  vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

# Should be provided by other file    
 # # Robot
 # max_vel_x: 0.4
 # max_vel_x_backwards: 0.2
 # max_vel_theta: 0.3
 # acc_lim_x: 0.5
 # acc_lim_theta: 0.5
 # min_turning_radius: 0.0
 # footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
 #   type: "point"
 #   radius: 0.2 # for type "circular"
 #   line_start: [-0.3, 0.0] # for type "line"
 #   line_end: [0.3, 0.0] # for type "line"
 #   front_offset: 0.2 # for type "two_circles"
 #   front_radius: 0.2 # for type "two_circles"
 #   rear_offset: 0.2 # for type "two_circles"
 #   rear_radius: 0.2 # for type "two_circles"
 #   vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

 # GoalTolerance
 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.1
 free_goal_vel: False
    
 # Obstacles
 min_obstacle_dist: 0.4
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 alternative_time_cost: False # not in use yet

 # Homotopy Class Planner
 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False

# TrajectoryPlannerROS:
#   # base vel/accel profile is in robot folders
#   # tolerances (defaults)
#   yaw_goal_tolerance: 0.1
#   xy_goal_tolerance: 0.1
#   latch_xy_goal_tolerance: true
#   # forward simulation
#   sim_time: 1.0
#   sim_granularity: 0.025
#   angular_sim_granularity: 0.025
#   vx_samples: 3
#   vtheta_samples: 10
#   # scoring (defaults)
#   meter_scoring: true
#   path_distance_bias: 0.5
#   goal_distance_bias: 0.75
#   occdist_scale: 0.00625
#   heading_lookahead: 0.325
#   heading_scoring_timestep: 0.8
#   heading_scoring: true
#   dwa: false
#   # other
#   oscillation_reset_dist: 0.05
#   # debug
#   publish_cost_grid_pc: false